/*
    Project: SnowPro Core Enablement Platform
    Purpose: Create certification, exam-domain, topic, and learning-path tables.
*/

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE SNOWPRO_LEARNING_WH;
USE DATABASE SNOWPRO_ENABLEMENT;
USE SCHEMA CORE;

-- Stores supported certifications.
CREATE TABLE IF NOT EXISTS CERTIFICATIONS (
    CERTIFICATION_ID       VARCHAR(20)  NOT NULL,
    CERTIFICATION_CODE     VARCHAR(50)  NOT NULL,
    CERTIFICATION_NAME     VARCHAR(200) NOT NULL,
    EXAM_VERSION           VARCHAR(50),
    DESCRIPTION            VARCHAR(1000),
    ACTIVE_FLAG            BOOLEAN      DEFAULT TRUE,
    CREATED_AT             TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT             TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_CERTIFICATIONS PRIMARY KEY (CERTIFICATION_ID)
)
COMMENT = 'Certifications supported by the learning platform';

-- Stores the four learner experience categories.
CREATE TABLE IF NOT EXISTS EXPERIENCE_LEVELS (
    EXPERIENCE_LEVEL_CODE  VARCHAR(20)  NOT NULL,
    EXPERIENCE_LEVEL_NAME  VARCHAR(100) NOT NULL,
    MIN_YEARS              NUMBER(3,1),
    MAX_YEARS              NUMBER(3,1),
    RECOMMENDED_WEEKS      NUMBER(3,0)  NOT NULL,
    WEEKLY_STUDY_HOURS     NUMBER(3,0)  NOT NULL,
    DISPLAY_ORDER          NUMBER(2,0)  NOT NULL,
    ACTIVE_FLAG            BOOLEAN      DEFAULT TRUE,
    CREATED_AT             TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT             TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_EXPERIENCE_LEVELS PRIMARY KEY (EXPERIENCE_LEVEL_CODE)
)
COMMENT = 'Configurable study duration for each experience level';

-- Stores the official exam domains.
CREATE TABLE IF NOT EXISTS EXAM_DOMAINS (
    DOMAIN_ID              VARCHAR(20)   NOT NULL,
    CERTIFICATION_ID       VARCHAR(20)   NOT NULL,
    DOMAIN_NAME            VARCHAR(200)  NOT NULL,
    EXAM_WEIGHT_PERCENT    NUMBER(5,2),
    DOMAIN_ORDER           NUMBER(2,0)   NOT NULL,
    DESCRIPTION            VARCHAR(1000),
    ACTIVE_FLAG            BOOLEAN       DEFAULT TRUE,
    CREATED_AT             TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT             TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_EXAM_DOMAINS PRIMARY KEY (DOMAIN_ID),
    CONSTRAINT FK_DOMAIN_CERTIFICATION
        FOREIGN KEY (CERTIFICATION_ID)
        REFERENCES CERTIFICATIONS (CERTIFICATION_ID)
)
COMMENT = 'SnowPro Core exam domains and their examination weights';

-- Stores individual study topics under each exam domain.
CREATE TABLE IF NOT EXISTS STUDY_TOPICS (
    TOPIC_ID               VARCHAR(30)   NOT NULL,
    DOMAIN_ID              VARCHAR(20)   NOT NULL,
    TOPIC_NAME             VARCHAR(250)  NOT NULL,
    TOPIC_DESCRIPTION      VARCHAR(2000),
    DIFFICULTY_LEVEL       VARCHAR(20),
    ESTIMATED_HOURS        NUMBER(5,1)   NOT NULL,
    TOPIC_ORDER            NUMBER(3,0)   NOT NULL,
    ACTIVE_FLAG            BOOLEAN       DEFAULT TRUE,
    CREATED_AT             TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT             TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_STUDY_TOPICS PRIMARY KEY (TOPIC_ID),
    CONSTRAINT FK_TOPIC_DOMAIN
        FOREIGN KEY (DOMAIN_ID)
        REFERENCES EXAM_DOMAINS (DOMAIN_ID)
)
COMMENT = 'Topics that learners must study for each exam domain';

-- Stores one learning path for each experience level.
CREATE TABLE IF NOT EXISTS LEARNING_PATHS (
    PATH_ID                VARCHAR(30)   NOT NULL,
    CERTIFICATION_ID       VARCHAR(20)   NOT NULL,
    EXPERIENCE_LEVEL_CODE  VARCHAR(20)   NOT NULL,
    PATH_NAME              VARCHAR(200)  NOT NULL,
    DURATION_WEEKS         NUMBER(3,0)   NOT NULL,
    WEEKLY_STUDY_HOURS     NUMBER(3,0)   NOT NULL,
    DESCRIPTION            VARCHAR(1000),
    ACTIVE_FLAG            BOOLEAN       DEFAULT TRUE,
    CREATED_AT             TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT             TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_LEARNING_PATHS PRIMARY KEY (PATH_ID),
    CONSTRAINT FK_PATH_CERTIFICATION
        FOREIGN KEY (CERTIFICATION_ID)
        REFERENCES CERTIFICATIONS (CERTIFICATION_ID),
    CONSTRAINT FK_PATH_EXPERIENCE_LEVEL
        FOREIGN KEY (EXPERIENCE_LEVEL_CODE)
        REFERENCES EXPERIENCE_LEVELS (EXPERIENCE_LEVEL_CODE)
)
COMMENT = 'Experience-based certification preparation paths';

-- Maps every topic to a planned week in each learning path.
CREATE TABLE IF NOT EXISTS PATH_TOPIC_PLAN (
    PATH_ID                VARCHAR(30)   NOT NULL,
    TOPIC_ID               VARCHAR(30)   NOT NULL,
    PLANNED_WEEK           NUMBER(3,0)   NOT NULL,
    RECOMMENDED_HOURS      NUMBER(5,1)   NOT NULL,
    REQUIRED_FLAG          BOOLEAN       DEFAULT TRUE,
    CREATED_AT             TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT             TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_PATH_TOPIC_PLAN PRIMARY KEY (PATH_ID, TOPIC_ID),
    CONSTRAINT FK_PLAN_PATH
        FOREIGN KEY (PATH_ID)
        REFERENCES LEARNING_PATHS (PATH_ID),
    CONSTRAINT FK_PLAN_TOPIC
        FOREIGN KEY (TOPIC_ID)
        REFERENCES STUDY_TOPICS (TOPIC_ID)
)
COMMENT = 'Weekly topic schedule for every experience-based learning path';

-- Validation command.
SHOW TABLES IN SCHEMA SNOWPRO_ENABLEMENT.CORE;