/*
    Project: SnowPro Core Enablement Platform
    Purpose: Create learner, enrollment, progress, resource,
             learning-event, and assessment tables.
*/

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE SNOWPRO_LEARNING_WH;
USE DATABASE SNOWPRO_ENABLEMENT;
USE SCHEMA CORE;

-- Stores certification preparation resources.
CREATE TABLE IF NOT EXISTS LEARNING_RESOURCES (
    RESOURCE_ID            VARCHAR(30)   NOT NULL,
    TOPIC_ID               VARCHAR(30)   NOT NULL,
    RESOURCE_TITLE         VARCHAR(300)  NOT NULL,
    RESOURCE_TYPE          VARCHAR(50)   NOT NULL,
    RESOURCE_URL           VARCHAR(1000),
    IS_OFFICIAL            BOOLEAN       DEFAULT FALSE,
    RESOURCE_ORDER         NUMBER(3,0),
    ACTIVE_FLAG            BOOLEAN       DEFAULT TRUE,
    CREATED_AT             TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT             TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_LEARNING_RESOURCES PRIMARY KEY (RESOURCE_ID),
    CONSTRAINT FK_RESOURCE_TOPIC
        FOREIGN KEY (TOPIC_ID)
        REFERENCES STUDY_TOPICS (TOPIC_ID)
)
COMMENT = 'Official documentation, videos, labs, and practice resources';

-- Stores learners using the platform.
CREATE TABLE IF NOT EXISTS LEARNERS (
    LEARNER_ID             VARCHAR(30)   NOT NULL,
    EMPLOYEE_ID            VARCHAR(50),
    LEARNER_NAME           VARCHAR(200)  NOT NULL,
    EMAIL                   VARCHAR(320)  NOT NULL,
    DEPARTMENT_NAME         VARCHAR(150),
    SNOWFLAKE_EXPERIENCE_YEARS NUMBER(4,1),
    EXPERIENCE_LEVEL_CODE  VARCHAR(20)   NOT NULL,
    JOINED_DATE             DATE         DEFAULT CURRENT_DATE(),
    ACTIVE_FLAG             BOOLEAN      DEFAULT TRUE,
    CREATED_AT              TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT              TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_LEARNERS PRIMARY KEY (LEARNER_ID),
    CONSTRAINT UQ_LEARNER_EMAIL UNIQUE (EMAIL),
    CONSTRAINT FK_LEARNER_EXPERIENCE_LEVEL
        FOREIGN KEY (EXPERIENCE_LEVEL_CODE)
        REFERENCES EXPERIENCE_LEVELS (EXPERIENCE_LEVEL_CODE)
)
COMMENT = 'Employees preparing for a supported certification';

-- Connects a learner to a certification and learning path.
CREATE TABLE IF NOT EXISTS ENROLLMENTS (
    ENROLLMENT_ID           VARCHAR(30)   NOT NULL,
    LEARNER_ID              VARCHAR(30)   NOT NULL,
    CERTIFICATION_ID        VARCHAR(20)   NOT NULL,
    PATH_ID                 VARCHAR(30)   NOT NULL,
    ENROLLED_DATE           DATE          NOT NULL,
    TARGET_COMPLETION_DATE  DATE,
    TARGET_EXAM_DATE        DATE,
    ENROLLMENT_STATUS       VARCHAR(30)   DEFAULT 'ACTIVE',
    CREATED_AT              TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT              TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_ENROLLMENTS PRIMARY KEY (ENROLLMENT_ID),
    CONSTRAINT FK_ENROLLMENT_LEARNER
        FOREIGN KEY (LEARNER_ID)
        REFERENCES LEARNERS (LEARNER_ID),
    CONSTRAINT FK_ENROLLMENT_CERTIFICATION
        FOREIGN KEY (CERTIFICATION_ID)
        REFERENCES CERTIFICATIONS (CERTIFICATION_ID),
    CONSTRAINT FK_ENROLLMENT_PATH
        FOREIGN KEY (PATH_ID)
        REFERENCES LEARNING_PATHS (PATH_ID)
)
COMMENT = 'Learner enrollment in a certification learning path';

-- Stores the current completion status of each topic.
CREATE TABLE IF NOT EXISTS TOPIC_PROGRESS (
    ENROLLMENT_ID           VARCHAR(30)   NOT NULL,
    TOPIC_ID                VARCHAR(30)   NOT NULL,
    PROGRESS_STATUS         VARCHAR(30)   DEFAULT 'NOT_STARTED',
    COMPLETION_PERCENT      NUMBER(5,2)   DEFAULT 0,
    HOURS_SPENT             NUMBER(7,2)   DEFAULT 0,
    STARTED_AT              TIMESTAMP_NTZ,
    COMPLETED_AT            TIMESTAMP_NTZ,
    LAST_ACTIVITY_AT        TIMESTAMP_NTZ,
    UPDATED_AT              TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_TOPIC_PROGRESS PRIMARY KEY (ENROLLMENT_ID, TOPIC_ID),
    CONSTRAINT FK_PROGRESS_ENROLLMENT
        FOREIGN KEY (ENROLLMENT_ID)
        REFERENCES ENROLLMENTS (ENROLLMENT_ID),
    CONSTRAINT FK_PROGRESS_TOPIC
        FOREIGN KEY (TOPIC_ID)
        REFERENCES STUDY_TOPICS (TOPIC_ID)
)
COMMENT = 'Latest progress of every learner for every assigned topic';

-- Stores individual learning activities for pipeline processing.
CREATE TABLE IF NOT EXISTS LEARNING_EVENTS (
    EVENT_ID                VARCHAR(50)   NOT NULL,
    ENROLLMENT_ID           VARCHAR(30)   NOT NULL,
    TOPIC_ID                VARCHAR(30)   NOT NULL,
    EVENT_TYPE              VARCHAR(50)   NOT NULL,
    EVENT_TIMESTAMP         TIMESTAMP_NTZ NOT NULL,
    DURATION_MINUTES        NUMBER(8,0),
    COMPLETION_PERCENT      NUMBER(5,2),
    EVENT_SOURCE            VARCHAR(100),
    NOTES                   VARCHAR(1000),
    PROCESSED_AT            TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_LEARNING_EVENTS PRIMARY KEY (EVENT_ID),
    CONSTRAINT FK_EVENT_ENROLLMENT
        FOREIGN KEY (ENROLLMENT_ID)
        REFERENCES ENROLLMENTS (ENROLLMENT_ID),
    CONSTRAINT FK_EVENT_TOPIC
        FOREIGN KEY (TOPIC_ID)
        REFERENCES STUDY_TOPICS (TOPIC_ID)
)
COMMENT = 'Validated learner activities processed by the data pipeline';

-- Stores quiz, practice test, and mock exam results.
CREATE TABLE IF NOT EXISTS ASSESSMENT_RESULTS (
    ASSESSMENT_ID           VARCHAR(50)   NOT NULL,
    ENROLLMENT_ID           VARCHAR(30)   NOT NULL,
    ASSESSMENT_NAME         VARCHAR(250)  NOT NULL,
    ASSESSMENT_TYPE         VARCHAR(50)   NOT NULL,
    DOMAIN_ID               VARCHAR(20),
    SCORE_PERCENT           NUMBER(5,2)   NOT NULL,
    PASSED_FLAG             BOOLEAN,
    ATTEMPTED_AT            TIMESTAMP_NTZ NOT NULL,
    NOTES                   VARCHAR(1000),
    CREATED_AT              TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_ASSESSMENT_RESULTS PRIMARY KEY (ASSESSMENT_ID),
    CONSTRAINT FK_ASSESSMENT_ENROLLMENT
        FOREIGN KEY (ENROLLMENT_ID)
        REFERENCES ENROLLMENTS (ENROLLMENT_ID),
    CONSTRAINT FK_ASSESSMENT_DOMAIN
        FOREIGN KEY (DOMAIN_ID)
        REFERENCES EXAM_DOMAINS (DOMAIN_ID)
)
COMMENT = 'Learner quiz, practice-test, and mock-exam results';

-- Validation command.
SHOW TABLES IN SCHEMA SNOWPRO_ENABLEMENT.CORE;