/*==============================================================================
  Snowflake Certification Enablement Platform
  Step 19: Role-based access control

  Roles:
  - FR_CERT_ENABLEMENT_LEARNER_DEV
  - FR_CERT_ENABLEMENT_PROGRAM_MANAGER_DEV
  - FR_CERT_ENABLEMENT_PLATFORM_ADMIN_DEV

  User assignments are intentionally excluded from Git.
==============================================================================*/

USE ROLE ACCOUNTADMIN;


/*------------------------------------------------------------------------------
  1. Create the platform roles
------------------------------------------------------------------------------*/

CREATE ROLE IF NOT EXISTS FR_CERT_ENABLEMENT_LEARNER_DEV;

CREATE ROLE IF NOT EXISTS FR_CERT_ENABLEMENT_PROGRAM_MANAGER_DEV;

CREATE ROLE IF NOT EXISTS FR_CERT_ENABLEMENT_PLATFORM_ADMIN_DEV;


/*------------------------------------------------------------------------------
  2. Create the role hierarchy

  PLATFORM_ADMIN
        ↓
  PROGRAM_MANAGER
        ↓
  LEARNER
------------------------------------------------------------------------------*/

GRANT ROLE FR_CERT_ENABLEMENT_LEARNER_DEV
TO ROLE FR_CERT_ENABLEMENT_PROGRAM_MANAGER_DEV;

GRANT ROLE FR_CERT_ENABLEMENT_PROGRAM_MANAGER_DEV
TO ROLE FR_CERT_ENABLEMENT_PLATFORM_ADMIN_DEV;

GRANT ROLE FR_CERT_ENABLEMENT_PLATFORM_ADMIN_DEV
TO ROLE SYSADMIN;


/*------------------------------------------------------------------------------
  3. Common warehouse and database access
------------------------------------------------------------------------------*/

GRANT USAGE
ON WAREHOUSE WH_CERT_ENABLEMENT_DEV_XS
TO ROLE FR_CERT_ENABLEMENT_LEARNER_DEV;

GRANT USAGE
ON WAREHOUSE WH_CERT_ENABLEMENT_DEV_XS
TO ROLE FR_CERT_ENABLEMENT_PROGRAM_MANAGER_DEV;

GRANT USAGE, OPERATE, MONITOR
ON WAREHOUSE WH_CERT_ENABLEMENT_DEV_XS
TO ROLE FR_CERT_ENABLEMENT_PLATFORM_ADMIN_DEV;


GRANT USAGE
ON DATABASE DB_CERT_ENABLEMENT_DEV
TO ROLE FR_CERT_ENABLEMENT_LEARNER_DEV;

GRANT USAGE
ON DATABASE DB_CERT_ENABLEMENT_DEV
TO ROLE FR_CERT_ENABLEMENT_PROGRAM_MANAGER_DEV;

GRANT USAGE
ON DATABASE DB_CERT_ENABLEMENT_DEV
TO ROLE FR_CERT_ENABLEMENT_PLATFORM_ADMIN_DEV;


/*------------------------------------------------------------------------------
  4. Learner permissions

  Learners can:
  - View the common weekly study plans.
  - Record their learning activity through the controlled procedure.

  Learners are not given direct access to personal learner tables.
------------------------------------------------------------------------------*/

GRANT USAGE
ON SCHEMA DB_CERT_ENABLEMENT_DEV.ANALYTICS
TO ROLE FR_CERT_ENABLEMENT_LEARNER_DEV;

GRANT USAGE
ON SCHEMA DB_CERT_ENABLEMENT_DEV.CONTROL
TO ROLE FR_CERT_ENABLEMENT_LEARNER_DEV;

GRANT SELECT
ON VIEW DB_CERT_ENABLEMENT_DEV.ANALYTICS.VW_WEEKLY_STUDY_PLAN
TO ROLE FR_CERT_ENABLEMENT_LEARNER_DEV;

GRANT USAGE
ON PROCEDURE
DB_CERT_ENABLEMENT_DEV.CONTROL.SP_RECORD_CERT_ENABLEMENT_LEARNING_ACTIVITY(
    VARCHAR,
    VARCHAR,
    VARCHAR,
    NUMBER,
    NUMBER,
    VARCHAR
)
TO ROLE FR_CERT_ENABLEMENT_LEARNER_DEV;


/*------------------------------------------------------------------------------
  5. Program-manager permissions

  Program managers can:
  - View all analytics.
  - Register learners.
  - Record learning activities.
  - Record and maintain assessment results.
------------------------------------------------------------------------------*/

GRANT USAGE
ON SCHEMA DB_CERT_ENABLEMENT_DEV.CORE
TO ROLE FR_CERT_ENABLEMENT_PROGRAM_MANAGER_DEV;

GRANT USAGE
ON SCHEMA DB_CERT_ENABLEMENT_DEV.ANALYTICS
TO ROLE FR_CERT_ENABLEMENT_PROGRAM_MANAGER_DEV;

GRANT USAGE
ON SCHEMA DB_CERT_ENABLEMENT_DEV.CONTROL
TO ROLE FR_CERT_ENABLEMENT_PROGRAM_MANAGER_DEV;


GRANT SELECT
ON ALL VIEWS IN SCHEMA DB_CERT_ENABLEMENT_DEV.ANALYTICS
TO ROLE FR_CERT_ENABLEMENT_PROGRAM_MANAGER_DEV;

GRANT SELECT
ON FUTURE VIEWS IN SCHEMA DB_CERT_ENABLEMENT_DEV.ANALYTICS
TO ROLE FR_CERT_ENABLEMENT_PROGRAM_MANAGER_DEV;


GRANT SELECT, INSERT, UPDATE
ON TABLE DB_CERT_ENABLEMENT_DEV.CORE.ASSESSMENT_RESULTS
TO ROLE FR_CERT_ENABLEMENT_PROGRAM_MANAGER_DEV;


GRANT USAGE
ON PROCEDURE
DB_CERT_ENABLEMENT_DEV.CONTROL.SP_REGISTER_CERT_ENABLEMENT_LEARNER(
    VARCHAR,
    VARCHAR,
    VARCHAR,
    VARCHAR,
    NUMBER
)
TO ROLE FR_CERT_ENABLEMENT_PROGRAM_MANAGER_DEV;

GRANT USAGE
ON PROCEDURE
DB_CERT_ENABLEMENT_DEV.CONTROL.SP_RECORD_CERT_ENABLEMENT_LEARNING_ACTIVITY(
    VARCHAR,
    VARCHAR,
    VARCHAR,
    NUMBER,
    NUMBER,
    VARCHAR
)
TO ROLE FR_CERT_ENABLEMENT_PROGRAM_MANAGER_DEV;


/*------------------------------------------------------------------------------
  6. Platform-administrator permissions
------------------------------------------------------------------------------*/

GRANT ALL PRIVILEGES
ON SCHEMA DB_CERT_ENABLEMENT_DEV.RAW
TO ROLE FR_CERT_ENABLEMENT_PLATFORM_ADMIN_DEV;

GRANT ALL PRIVILEGES
ON SCHEMA DB_CERT_ENABLEMENT_DEV.CORE
TO ROLE FR_CERT_ENABLEMENT_PLATFORM_ADMIN_DEV;

GRANT ALL PRIVILEGES
ON SCHEMA DB_CERT_ENABLEMENT_DEV.ANALYTICS
TO ROLE FR_CERT_ENABLEMENT_PLATFORM_ADMIN_DEV;

GRANT ALL PRIVILEGES
ON SCHEMA DB_CERT_ENABLEMENT_DEV.CONTROL
TO ROLE FR_CERT_ENABLEMENT_PLATFORM_ADMIN_DEV;


GRANT ALL PRIVILEGES
ON ALL TABLES IN SCHEMA DB_CERT_ENABLEMENT_DEV.RAW
TO ROLE FR_CERT_ENABLEMENT_PLATFORM_ADMIN_DEV;

GRANT ALL PRIVILEGES
ON ALL TABLES IN SCHEMA DB_CERT_ENABLEMENT_DEV.CORE
TO ROLE FR_CERT_ENABLEMENT_PLATFORM_ADMIN_DEV;

GRANT ALL PRIVILEGES
ON ALL TABLES IN SCHEMA DB_CERT_ENABLEMENT_DEV.CONTROL
TO ROLE FR_CERT_ENABLEMENT_PLATFORM_ADMIN_DEV;


GRANT ALL PRIVILEGES
ON FUTURE TABLES IN SCHEMA DB_CERT_ENABLEMENT_DEV.RAW
TO ROLE FR_CERT_ENABLEMENT_PLATFORM_ADMIN_DEV;

GRANT ALL PRIVILEGES
ON FUTURE TABLES IN SCHEMA DB_CERT_ENABLEMENT_DEV.CORE
TO ROLE FR_CERT_ENABLEMENT_PLATFORM_ADMIN_DEV;

GRANT ALL PRIVILEGES
ON FUTURE TABLES IN SCHEMA DB_CERT_ENABLEMENT_DEV.CONTROL
TO ROLE FR_CERT_ENABLEMENT_PLATFORM_ADMIN_DEV;


GRANT ALL PRIVILEGES
ON ALL VIEWS IN SCHEMA DB_CERT_ENABLEMENT_DEV.ANALYTICS
TO ROLE FR_CERT_ENABLEMENT_PLATFORM_ADMIN_DEV;

GRANT ALL PRIVILEGES
ON FUTURE VIEWS IN SCHEMA DB_CERT_ENABLEMENT_DEV.ANALYTICS
TO ROLE FR_CERT_ENABLEMENT_PLATFORM_ADMIN_DEV;


GRANT USAGE
ON ALL PROCEDURES IN SCHEMA DB_CERT_ENABLEMENT_DEV.CONTROL
TO ROLE FR_CERT_ENABLEMENT_PLATFORM_ADMIN_DEV;

GRANT USAGE
ON FUTURE PROCEDURES IN SCHEMA DB_CERT_ENABLEMENT_DEV.CONTROL
TO ROLE FR_CERT_ENABLEMENT_PLATFORM_ADMIN_DEV;


GRANT OPERATE, MONITOR
ON ALL TASKS IN SCHEMA DB_CERT_ENABLEMENT_DEV.CONTROL
TO ROLE FR_CERT_ENABLEMENT_PLATFORM_ADMIN_DEV;

GRANT OPERATE, MONITOR
ON FUTURE TASKS IN SCHEMA DB_CERT_ENABLEMENT_DEV.CONTROL
TO ROLE FR_CERT_ENABLEMENT_PLATFORM_ADMIN_DEV;


/*------------------------------------------------------------------------------
  7. Verify the role grants
------------------------------------------------------------------------------*/

SHOW GRANTS TO ROLE FR_CERT_ENABLEMENT_LEARNER_DEV;

SHOW GRANTS TO ROLE FR_CERT_ENABLEMENT_PROGRAM_MANAGER_DEV;

SHOW GRANTS TO ROLE FR_CERT_ENABLEMENT_PLATFORM_ADMIN_DEV;


/*------------------------------------------------------------------------------
  Assign roles to actual users separately.

  Do not add real usernames to this Git file.

  Example only:

  GRANT ROLE FR_CERT_ENABLEMENT_LEARNER_DEV TO USER <username>;
  GRANT ROLE FR_CERT_ENABLEMENT_PROGRAM_MANAGER_DEV TO USER <username>;
  GRANT ROLE FR_CERT_ENABLEMENT_PLATFORM_ADMIN_DEV TO USER <username>;
------------------------------------------------------------------------------*/